Outlined files and working on bug fix
This is the error vscode is throwing:   Parsing error: Cannot find module next/babel
Require stack:
- /Users/joe/Desktop/git projects/exercise-app-repo/exercise-app/node_modules/next/dist/compiled/babel/bundle.js
- /Users/joe/Desktop/git projects/exercise-app-repo/exercise-app/node_modules/next/dist/compiled/babel/eslint-parser.js
- /Users/joe/Desktop/git projects/exercise-app-repo/exercise-app/node_modules/eslint-config-next/parser.js
- /Users/joe/Desktop/git projects/exercise-app-repo/exercise-app/node_modules/@eslint/eslintrc/dist/eslintrc.cjseslint